# Generated by Django 5.2.1 on 2025-05-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ubicaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cultivos",
            fields=[
                ("id_cultivo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_cultivo", models.CharField(max_length=100)),
                ("fecha_siembra", models.DateField(blank=True, null=True)),
                ("fecha_cosecha", models.DateField(blank=True, null=True)),
                ("profundidad_radicular", models.FloatField(blank=True, null=True)),
                ("factor_agotamiento", models.FloatField(blank=True, null=True)),
                ("factor_respuesta", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "cultivos",
            },
        ),
        migrations.CreateModel(
            name="CultivoSuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_cultivo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cultivo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cultivos.cultivos",
                    ),
                ),
                (
                    "id_suelo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_suelo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ubicaciones.suelo",
                    ),
                ),
            ],
            options={
                "db_table": "cultivo_suelo",
            },
        ),
        migrations.CreateModel(
            name="CultivoUbicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_cultivo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cultivo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cultivos.cultivos",
                    ),
                ),
                (
                    "id_ubicacion",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_ubicacion",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ubicaciones.ubicacion",
                    ),
                ),
            ],
            options={
                "db_table": "cultivo_ubicacion",
            },
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                ("id_etapa", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_etapa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("diametro_cultivo", models.FloatField(blank=True, null=True)),
                ("kc_inicial", models.FloatField(blank=True, null=True)),
                ("kc_medio", models.FloatField(blank=True, null=True)),
                ("kc_final", models.FloatField(blank=True, null=True)),
                (
                    "id_cultivo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cultivo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cultivos.cultivos",
                    ),
                ),
            ],
            options={
                "db_table": "etapas",
            },
        ),
    ]
