# Generated by Django 5.2.6 on 2026-01-28 04:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_eto_method', models.CharField(choices=[('HARGREAVES', 'Hargreaves-Samani (Solo Temperatura)'), ('PENMAN', 'Penman-Monteith (Requiere Viento/Humedad)')], default='HARGREAVES', max_length=20)),
                ('effective_rain_method', models.CharField(choices=[('USDA', 'USDA S.C. Method (Recomendado)'), ('FIXED', 'Porcentaje Fijo (Ej: 80%)'), ('DEPENDABLE', 'Lluvia Confiable (FAO)')], default='USDA', max_length=20)),
                ('system_efficiency', models.FloatField(default=0.9, help_text='0.90 para Goteo, 0.75 para Aspersión, 0.60 Gravedad', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True, verbose_name='T Max (°C)')),
                ('temp_min', models.FloatField(blank=True, null=True, verbose_name='T Min (°C)')),
                ('humidity_mean', models.FloatField(blank=True, null=True, verbose_name='Humedad Relativa (%)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Velocidad Viento (m/s)')),
                ('solar_rad', models.FloatField(blank=True, null=True, verbose_name='Radiación Solar (MJ/m2/d)')),
                ('eto_mm', models.FloatField(help_text='Evapotranspiración de Referencia', verbose_name='ETo (mm/día)')),
                ('source', models.CharField(choices=[('NASA', 'NASA POWER API'), ('STATION', 'Estación Local / Sensor'), ('MANUAL', 'Ingreso Manual')], default='NASA', max_length=10)),
                ('is_manual_override', models.BooleanField(default=False, help_text='Si es True, la API no sobreescribirá este dato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clima Diario Operativo',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
