# Generated by Django 5.2.1 on 2025-06-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eto",
            fields=[
                ("id_eto", models.AutoField(primary_key=True, serialize=False)),
                ("country", models.CharField(max_length=100)),
                ("station_name", models.CharField(max_length=100)),
                ("altitude", models.FloatField(help_text="on meters above sea level")),
                ("latitude", models.FloatField(help_text="in decimal degrees")),
                ("longitude", models.FloatField(help_text="in decimal degrees")),
                ("maximum_temperature", models.FloatField()),
                ("minimum_temperature", models.FloatField()),
                ("relative_humitidy", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("sunshine_hours", models.FloatField()),
                ("reference_evapotranspiration", models.FloatField()),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("penman-monteith", "FAO Penman-Monteith"),
                            ("hargreaves", "Hargreaves-Samani (1985)"),
                            ("turc", "Turc"),
                            ("makkink", "Makkink (1957)"),
                            ("makkink-abstew", "Makkink-Abstew"),
                            ("simple-abstew", "Simple Abstew (1996)"),
                            ("priestley-taylor", "Priestley-Taylor"),
                            ("ivanov", "Ivanov (1954)"),
                            ("christiansen", "Christiansen"),
                        ],
                        default="penman-monteith",
                        help_text="Method used to calculate reference evapotranspiration",
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "eto",
            },
        ),
    ]
