# Generated by Django 5.2.6 on 2025-09-09 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetereologicalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField()),
                ("daily_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meteorological_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("start_date", "end_date", "latitude", "longitude", "user")
                },
            },
        ),
        migrations.CreateModel(
            name="MetereologicalSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_type", models.CharField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("average_temp_max", models.FloatField(blank=True, null=True)),
                ("average_temp_min", models.FloatField(blank=True, null=True)),
                ("average_temp", models.FloatField(blank=True, null=True)),
                ("average_relative_humidity", models.FloatField(blank=True, null=True)),
                ("average_radiation_solar", models.FloatField(blank=True, null=True)),
                ("average_wind_speed", models.FloatField(blank=True, null=True)),
                (
                    "data_source",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("API", "API")], max_length=10
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "unique_together": {
                    ("start_date", "end_date", "latitude", "longitude")
                },
            },
        ),
        migrations.CreateModel(
            name="EtoCalculated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("penman-monteith", "FAO Penman-Monteith"),
                            ("hargreaves", "Hargreaves-Samani (1985)"),
                            ("turc", "Turc"),
                            ("makkink", "Makkink (1957)"),
                            ("makkink-abstew", "Makkink-Abstew"),
                            ("simple-abstew", "Simple Abstew (1996)"),
                            ("priestley-taylor", "Priestley-Taylor"),
                            ("ivanov", "Ivanov (1954)"),
                            ("christiansen", "Christiansen"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        choices=[("MANUAL", "Manual"), ("API", "API")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("calculation_date", models.DateField(blank=True, null=True)),
                ("eto", models.FloatField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "daily_data",
                    models.ManyToManyField(
                        blank=True, to="climate_and_eto.dailymetereologicaldata"
                    ),
                ),
                (
                    "summary_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="climate_and_eto.metereologicalsummary",
                    ),
                ),
            ],
        ),
    ]
