# Generated by Django 5.2.1 on 2025-06-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climate_and_eto", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eto",
            old_name="relative_humitidy",
            new_name="relative_humidity",
        ),
    ]
