# Generated by Django 5.2.6 on 2026-01-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_and_eto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationsettings',
            name='preferred_eto_method',
            field=models.CharField(choices=[('HARGREAVES', 'Hargreaves-Samani (Solo Temperatura)'), ('PENMAN', 'Penman-Monteith (Estándar FAO / Completo)'), ('TURC', 'Turc (Climas Húmedos)'), ('MAKKINK', 'Makkink (Radiación y Temp)'), ('MAKKINK_ABSTEW', 'Makkink-Abstew (Calibrado)'), ('PRIESTLEY', 'Priestley-Taylor (Sin Viento)'), ('IVANOV', 'Ivanov (Humedad y Temp)'), ('CHRISTIANSEN', 'Christiansen (Datos Completos)')], default='PENMAN', max_length=30),
        ),
    ]
