# Generated by Django 5.2.1 on 2025-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate_and_eto", "0002_rename_relative_humitidy_eto_relative_humidity"),
    ]

    operations = [
        migrations.AddField(
            model_name="eto",
            name="maximum_temperature_daily",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eto",
            name="minimum_temperature_daily",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eto",
            name="relative_humidity_daily",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eto",
            name="sunshine_hours_daily",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eto",
            name="wind_speed_daily",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eto",
            name="maximum_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eto",
            name="minimum_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eto",
            name="relative_humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eto",
            name="sunshine_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eto",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
