# Generated by Django 5.2.9 on 2026-02-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_and_eto', '0002_alter_irrigationsettings_preferred_eto_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationsettings',
            name='preferred_eto_method',
            field=models.CharField(choices=[('PENMAN', 'Penman-Monteith (FAO-56)'), ('HARGREAVES', 'Hargreaves-Samani'), ('TURC', 'Turc (Zonas Húmedas)'), ('MAKKINK', 'Makkink (Radiación)'), ('MAKKINK_ABSTEW', 'Makkink-Abstew (Calibrado)'), ('PRIESTLEY', 'Priestley-Taylor (Sin Viento)'), ('IVANOV', 'Ivanov (Humedad y Temp)'), ('CHRISTIANSEN', 'Christiansen (Datos Completos)'), ('SIMPLE_ABSTEW', 'Simple Abstew')], default='PENMAN', max_length=30),
        ),
    ]
