# Generated by Django 5.2.1 on 2025-06-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climate_and_eto", "0003_eto_maximum_temperature_daily_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eto",
            old_name="maximum_temperature",
            new_name="average_max_temp",
        ),
        migrations.RenameField(
            model_name="eto",
            old_name="minimum_temperature",
            new_name="average_relavite_humidity",
        ),
        migrations.RenameField(
            model_name="eto",
            old_name="relative_humidity",
            new_name="average_sunshine_hours",
        ),
        migrations.RenameField(
            model_name="eto",
            old_name="sunshine_hours",
            new_name="average_wind_speed",
        ),
        migrations.RenameField(
            model_name="eto",
            old_name="wind_speed",
            new_name="avergae_min_temp",
        ),
    ]
