# Generated by Django 5.2.9 on 2026-02-07 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_and_eto', '0004_alter_dailyweather_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estudio')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('result_data', models.JSONField(verbose_name='Datos Calculados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudio Climático',
                'ordering': ['-created_at'],
            },
        ),
    ]
