# Generated by Django 5.2.1 on 2025-06-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "climate_and_eto",
            "0004_rename_maximum_temperature_eto_average_max_temp_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="eto",
            old_name="average_relavite_humidity",
            new_name="average_min_temp",
        ),
        migrations.RenameField(
            model_name="eto",
            old_name="avergae_min_temp",
            new_name="average_relative_humidity",
        ),
    ]
