# Generated by Django 5.2.9 on 2026-02-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_and_eto', '0005_climatestudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweather',
            name='source',
            field=models.CharField(choices=[('NASA', 'NASA POWER API'), ('SATELLITE', 'Satelital (NASA)'), ('STATION', 'Estación Local / Sensor'), ('MANUAL', 'Ingreso Manual')], default='NASA', max_length=20),
        ),
    ]
