# Generated by Django 5.2.9 on 2026-02-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_and_eto', '0006_alter_dailyweather_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyweather',
            name='method',
            field=models.CharField(blank=True, default='PENMAN', help_text='Fórmula usada para calcular la ETo', max_length=50, null=True),
        ),
    ]
