# Generated by Django 5.2.11 on 2026-02-27 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_and_eto', '0007_dailyweather_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationsettings',
            name='experience_criterion',
            field=models.FloatField(default=80.0, help_text='% de la distancia entre plantas para calcular diámetro de sombra', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
    ]
