# Generated by Django 5.2.11 on 2026-03-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_and_eto', '0008_irrigationsettings_experience_criterion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationsettings',
            name='experience_criterion',
        ),
    ]
