# Generated by Django 5.2.6 on 2025-09-19 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("kc_inicial", models.FloatField()),
                ("kc_desarrollo", models.FloatField()),
                ("kc_medio", models.FloatField()),
                ("kc_fin", models.FloatField()),
                (
                    "etapa_inicial",
                    models.IntegerField(help_text="Duración etapa inicial (días)"),
                ),
                (
                    "etapa_desarrollo",
                    models.IntegerField(help_text="Duración etapa desarrollo (días)"),
                ),
                (
                    "etapa_medio",
                    models.IntegerField(help_text="Duración etapa media (días)"),
                ),
                (
                    "etapa_final",
                    models.IntegerField(
                        help_text="Duración etapa final/fin de temporada (días)"
                    ),
                ),
                (
                    "prof_radicular_ini",
                    models.FloatField(help_text="Profundidad radicular inicial (m)"),
                ),
                (
                    "prof_radicular_desarrollo",
                    models.FloatField(help_text="Profundidad radicular desarrollo (m)"),
                ),
                (
                    "prof_radicular_medio",
                    models.FloatField(help_text="Profundidad radicular media (m)"),
                ),
                (
                    "prof_radicular_final",
                    models.FloatField(help_text="Profundidad radicular final (m)"),
                ),
                (
                    "agotam_critico",
                    models.FloatField(help_text="Agotamiento crítico (fracción)"),
                ),
                (
                    "factor_respuesta_rend",
                    models.FloatField(help_text="Factor de respuesta a rendimiento"),
                ),
                (
                    "altura_min",
                    models.FloatField(help_text="Altura mínima del cultivo (m)"),
                ),
                (
                    "altura_max",
                    models.FloatField(help_text="Altura máxima del cultivo (m)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropToPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_siembra", models.DateField()),
                ("fecha_cosecha", models.DateField()),
                (
                    "altura",
                    models.FloatField(
                        help_text="Altura seleccionada por el usuario (m)"
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantaciones",
                        to="cultivo.crop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
