# Generated by Django 5.2.6 on 2026-01-28 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suelo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('kc_inicial', models.FloatField()),
                ('kc_medio', models.FloatField()),
                ('kc_fin', models.FloatField()),
                ('etapa_inicial', models.IntegerField(help_text='Duración etapa inicial (días)')),
                ('etapa_desarrollo', models.IntegerField(help_text='Duración etapa desarrollo (días)')),
                ('etapa_medio', models.IntegerField(help_text='Duración etapa media (días)')),
                ('etapa_final', models.IntegerField(help_text='Duración etapa final (días)')),
                ('prof_radicular_ini', models.FloatField(help_text='Profundidad radicular inicial (m)')),
                ('prof_radicular_max', models.FloatField(help_text='Profundidad radicular maxima (m)')),
                ('agotam_critico', models.FloatField(help_text='Fracción p (0.0 - 1.0)')),
                ('factor_respuesta_rend', models.FloatField(help_text='Factor de respuesta a rendimiento')),
                ('altura_max', models.FloatField(help_text='Altura máxima (m)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropToPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField()),
                ('fecha_cosecha_estimada', models.DateField(blank=True, null=True)),
                ('area', models.FloatField(default=1.0, help_text='Área sembrada en Hectáreas')),
                ('activo', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cultivo.crop')),
                ('soil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantings', to='suelo.soil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
