# Generated by Django 5.2.6 on 2026-01-28 03:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Fecha de Aplicación')),
                ('water_volume_mm', models.FloatField(verbose_name='Lámina Aplicada (mm)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Registro')),
                ('was_suggested', models.BooleanField(default=True, help_text='¿Siguió la recomendación del sistema?')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='cultivo.croptoplant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de Riego',
                'verbose_name_plural': 'Historial de Riegos',
                'ordering': ['-date', '-timestamp'],
            },
        ),
    ]
