# Generated by Django 5.2.6 on 2025-09-19 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cultivo", "0002_create_initial_crops"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="etapa_final",
            field=models.IntegerField(help_text="Duración etapa final (días)"),
        ),
        migrations.AlterField(
            model_name="croptoplant",
            name="altura",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="croptoplant",
            name="crop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cultivo.crop"
            ),
        ),
        migrations.AlterField(
            model_name="croptoplant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
