# Generated by Django 5.2.9 on 2026-02-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0003_load_fao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptoplant',
            name='densidad_calculada',
            field=models.FloatField(blank=True, editable=False, help_text='Plantas por Hectárea', null=True),
        ),
        migrations.AddField(
            model_name='croptoplant',
            name='distancia_plantas',
            field=models.FloatField(blank=True, help_text='Distancia entre plantas (metros)', null=True),
        ),
        migrations.AddField(
            model_name='croptoplant',
            name='distancia_surcos',
            field=models.FloatField(blank=True, help_text='Distancia entre surcos/hileras (metros)', null=True),
        ),
    ]
