# Generated by Django 5.2.11 on 2026-02-27 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_and_eto', '0008_irrigationsettings_experience_criterion'),
        ('cultivo', '0004_croptoplant_densidad_calculada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptoplant',
            name='eto_source',
            field=models.CharField(choices=[('DAILY', 'Operación Diaria (Tiempo Real)'), ('HISTORICAL', 'Estudio Histórico')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='croptoplant',
            name='historical_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate_and_eto.climatestudy'),
        ),
        migrations.AddField(
            model_name='croptoplant',
            name='manual_canopy_diameter',
            field=models.FloatField(blank=True, help_text='Diámetro de copa manual (m)', null=True),
        ),
    ]
