# Generated by Django 5.2.11 on 2026-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0005_croptoplant_eto_source_croptoplant_historical_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptoplant',
            name='historical_formula_choice',
            field=models.CharField(blank=True, help_text="Formula específica seleccionada dentro del estudio histórico (o 'AVERAGE_ALL')", max_length=30, null=True),
        ),
    ]
