# Generated by Django 5.2.1 on 2025-05-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suelo",
            fields=[
                ("id_suelo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_suelo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "textura_suelo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("capacidad_campo", models.FloatField(blank=True, null=True)),
                ("saturacion", models.FloatField(blank=True, null=True)),
                ("agua_disponible", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "suelos",
            },
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                ("id_ubicacion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_ubicacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pais_ubicacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
                ("altitud", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "ubicaciones",
            },
        ),
        migrations.CreateModel(
            name="Precipitacion",
            fields=[
                (
                    "id_precipitacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fecha", models.DateField(blank=True, null=True)),
                ("precipitacion_anual", models.FloatField(blank=True, null=True)),
                ("precipitacion_mensual", models.FloatField(blank=True, null=True)),
                ("precipitacion_total", models.FloatField(blank=True, null=True)),
                ("precipitacion_efectiva", models.FloatField(blank=True, null=True)),
                (
                    "id_ubicacion",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_ubicacion",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ubicaciones.ubicacion",
                    ),
                ),
            ],
            options={
                "db_table": "precipitaciones",
            },
        ),
        migrations.CreateModel(
            name="Eto",
            fields=[
                ("id_eto", models.AutoField(primary_key=True, serialize=False)),
                ("temperatura_maxima", models.FloatField(blank=True, null=True)),
                ("temperatura_minima", models.FloatField(blank=True, null=True)),
                ("humedad_relativa", models.FloatField(blank=True, null=True)),
                ("velocidad_viento", models.FloatField(blank=True, null=True)),
                ("horas_insolacion", models.FloatField(blank=True, null=True)),
                ("precipitacion", models.FloatField(blank=True, null=True)),
                (
                    "evapotranspiracion_potencial",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "id_ubicacion",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_ubicacion",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ubicaciones.ubicacion",
                    ),
                ),
            ],
            options={
                "db_table": "eto",
            },
        ),
    ]
