# Generated by Django 5.2.1 on 2025-05-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubicaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eto",
            options={"ordering": ["-fecha"]},
        ),
        migrations.AddField(
            model_name="eto",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
    ]
