# Generated by Django 5.2.1 on 2025-06-25 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cultivos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Riegos",
            fields=[
                ("id_riego", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_riego", models.DateField(blank=True, null=True)),
                ("cantidad_agua", models.FloatField(blank=True, null=True)),
                ("tipo_riego", models.CharField(blank=True, max_length=100, null=True)),
                ("eficiencia_riego", models.FloatField(blank=True, null=True)),
                (
                    "id_cultivo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cultivo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cultivos.cultivos",
                    ),
                ),
            ],
            options={
                "db_table": "riegos",
            },
        ),
    ]
