# Generated by Django 5.2.6 on 2026-01-27 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Lote Norte', max_length=100)),
                ('textura', models.CharField(help_text='Ej: Franco, Arcilloso', max_length=50)),
                ('capacidad_campo', models.FloatField(default=0.0, help_text='CC (% Vol)')),
                ('punto_marchitez', models.FloatField(default=0.0, help_text='PMP (% Vol)')),
                ('densidad_aparente', models.FloatField(default=1.2, help_text='Da (g/cm3)')),
                ('tasa_max_infiltracion', models.FloatField(default=0.0, help_text='mm/hora')),
                ('profundidad_radicular_max', models.FloatField(default=1.0, help_text='Metros')),
                ('humedad_disponible', models.FloatField(default=0.0, help_text='Calculado (CC - PMP)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
