# Generated by Django 5.2.6 on 2025-09-19 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Soil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "humedad_disponible",
                    models.FloatField(
                        help_text="Humedad de suelo disponible total (CC-PMP) en mm/metro"
                    ),
                ),
                (
                    "tasa_max_infiltracion",
                    models.FloatField(
                        help_text="Tasa máxima de infiltración de la precipitación en mm/día"
                    ),
                ),
                (
                    "profundidad_radicular_max",
                    models.FloatField(help_text="Profundidad radicular máxima en cm"),
                ),
                (
                    "agotamiento_inicial",
                    models.FloatField(
                        help_text="Agotamiento inicial de humedad de suelo (% de ADT)"
                    ),
                ),
                (
                    "humedad_inicial",
                    models.FloatField(
                        help_text="Humedad de suelo inicialmente disponible en mm/metro"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
