# Generated by Django 5.2.6 on 2026-01-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Decimal (Ej: 2.92)', null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='soil',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Decimal (Ej: -75.28)', null=True, verbose_name='Longitud'),
        ),
    ]
