# Generated by Django 5.2.6 on 2026-01-28 02:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Estación')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitud decimal (-90 a 90)', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitud decimal (-180 a 180)', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estación Pluviométrica',
                'verbose_name_plural': 'Estaciones',
            },
        ),
        migrations.CreateModel(
            name='PrecipitationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha de Registro')),
                ('precipitation_mm', models.FloatField(help_text='Lluvia bruta medida', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precipitación Total (mm)')),
                ('effective_precipitation_mm', models.FloatField(blank=True, help_text='Agua realmente aprovechable por la raíz', null=True, verbose_name='Precipitación Efectiva (mm)')),
                ('source', models.CharField(choices=[('MANUAL', 'Pluviómetro Manual'), ('CHIRPS', 'Satélite CHIRPS'), ('NASA', 'NASA POWER')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='precipitaciones.station')),
            ],
            options={
                'verbose_name': 'Registro de Lluvia',
                'ordering': ['-date'],
                'unique_together': {('station', 'date')},
            },
        ),
    ]
