# Generated by Django 5.2.11 on 2026-02-28 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precipitaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecipitationStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estudio')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('result_data', models.JSONField(verbose_name='Datos Calculados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='precipitaciones.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitation_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudio Pluviométrico',
                'verbose_name_plural': 'Estudios Pluviométricos',
                'ordering': ['-created_at'],
            },
        ),
    ]
