# Generated by Django 5.2.1 on 2025-05-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="apellido_usuario",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="contrasena_usuario",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="correo_usuario",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="nombre_usuario",
        ),
    ]
