# Generated by Django 5.2.1 on 2025-06-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="rol_usuario",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="tipo_usuario",
        ),
        migrations.DeleteModel(
            name="Roles",
        ),
    ]
